version: '3'
services:
  redis:
    container_name: redis-7000
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - 7000:7000
